version: "3.7"

networks:
  proxy:
    driver: bridge
    external: true

services:
  application:
    image: ${DOCKER_REGISTRY?}/${DOCKER_NAMESPACE?}/${DOCKER_IMAGE?}:${DOCKER_IMAGE_TAG?}
    restart: unless-stopped
    ports:
      - "${APPLICATION_HTTP_PORT:-80}:80"
      - "${APPLICATION_HTTPS_PORT:-443}:443"
    networks:
      - proxy
    environment:
      - APPLICATION_UID=${APPLICATION_USER_ID}
      - APPLICATION_GID=${APPLICATION_GROUP_ID}
      - PHP_POST_MAX_SIZE=${APPLICATION_PHP_POST_MAX_SIZE}
      - PHP_UPLOAD_MAX_FILESIZE=${APPLICATION_PHP_UPLOAD_MAX_FILESIZE}
      - SERVICE_NGINX_CLIENT_MAX_BODY_SIZE=${APPLICATION_SERVICE_NGINX_CLIENT_MAX_BODY_SIZE}
      - WEB_DOCUMENT_ROOT=${APPLICATION_WEB_DOCUMENT_ROOT:-/app}
      - WEB_ALIAS_DOMAIN=${APPLICATION_WEB_ALIAS_DOMAIN}
    volumes:
      - ${APPLICATION_PROJECT_DIR}:/app
      ## Uncomment if using laravel (custom your config)
      # - ${APPLICATION_CONFIG_DIR}/nginx/10-location-custom.conf:/opt/docker/etc/nginx/vhost.common.d/10-location-custom.conf:ro
      # - ${APPLICATION_CONFIG_DIR}/supervisor/worker.conf:/opt/docker/etc/supervisor.d/worker.conf:ro
